# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: main page
email: wqh1213@gmail.com
description: 生于忧患死于安乐
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
social:
    weibo:
    github: snailq
    twitter: snailq
# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

disqus_username: wqh19317

plugins: [jekyll-paginate]
paginate: 3
paginate_path: "page/:num/"

sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
